// P07B webhook client behavior using the compiled production ApiClient and WebhookApi modules.
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {ApiClient}=require('../../.evidence/ts/api.js');
const {WebhookApi}=require('../../.evidence/ts/webhook-api.js');
const cases=[];const test=(id,run)=>cases.push({id,run});
const endpoint='70000000-0000-0000-0000-000000000001';
const delivery='71000000-0000-0000-0000-000000000001';
const owner='72000000-0000-0000-0000-000000000001';
const event='73000000-0000-0000-0000-000000000001';
const csrf=token=>Response.json({headerName:'X-XSRF-TOKEN',token});
const endpointView={id:endpoint,ownerId:owner,destinationId:'sandbox-receiver',destinationUrl:'http://receiver:8081/events',enabled:true,version:1,createdAt:'2026-09-27T00:00:00Z',updatedAt:'2026-09-27T00:00:00Z'};
const deliveryView={id:delivery,endpointId:endpoint,ownerId:owner,destinationId:'sandbox-receiver',eventId:event,eventType:'transfer.settled',state:'FAILED',cycle:1,attempts:8,totalAttempts:8,nextAttemptAt:'2026-09-27T00:00:00Z',createdAt:'2026-09-27T00:00:00Z',updatedAt:'2026-09-27T00:00:00Z',lastError:'HTTP_503'};

test('P07BTS01-create-exposes-secret-only-in-command-result',async()=>{let observed;const api=new ApiClient(async(url,options)=>{if(url.endsWith('/auth/csrf'))return csrf('p07b-1');observed={url,method:options.method,body:JSON.parse(options.body)};return Response.json({endpoint:endpointView,signingSecret:'one-time-secret'},{status:201})});const result=await new WebhookApi(api).createEndpoint();assert.equal(result.status,201);assert.equal(result.body.signingSecret,'one-time-secret');assert.deepEqual(observed,{url:'/api/v1/webhook-endpoints',method:'POST',body:{destinationId:'sandbox-receiver'}});});

test('P07BTS02-state-and-rotation-carry-expected-version',async()=>{const seen=[];const api=new ApiClient(async(url,options)=>{if(url.endsWith('/auth/csrf'))return csrf('p07b-2');seen.push([url,JSON.parse(options.body)]);return Response.json(url.endsWith('rotate-secret')?{endpoint:{...endpointView,version:3},signingSecret:'rotated'}:{...endpointView,enabled:false,version:2})});const webhooks=new WebhookApi(api);await webhooks.setEndpointState(endpoint.toUpperCase(),false,1);await webhooks.rotateSecret(endpoint,2);assert.deepEqual(seen,[[`/api/v1/webhook-endpoints/${endpoint}/state`,{enabled:false,expectedVersion:1}],[`/api/v1/webhook-endpoints/${endpoint}/rotate-secret`,{expectedVersion:2}]]);});

test('P07BTS03-owner-delivery-inspection-is-bounded-and-deterministic',async()=>{const paths=[];const detail={delivery:deliveryView,attempts:[]};const api=new ApiClient(async url=>{paths.push(url);return Response.json(url.includes('/deliveries?')?{items:[deliveryView],limit:10,offset:0,hasMore:false}:detail)});const webhooks=new WebhookApi(api);assert.equal((await webhooks.deliveries(endpoint,10,0)).items[0].eventId,event);assert.equal((await webhooks.delivery(delivery)).delivery.id,delivery);assert.deepEqual(paths,[`/api/v1/webhook-endpoints/${endpoint}/deliveries?limit=10&offset=0`,`/api/v1/webhook-deliveries/${delivery}`]);});

test('P07BTS04-manual-retry-normalizes-reason',async()=>{let observed;const detail={delivery:{...deliveryView,state:'PENDING',cycle:2,attempts:0},attempts:[]};const api=new ApiClient(async(url,options)=>{if(url.endsWith('/auth/csrf'))return csrf('p07b-4');observed={url,body:JSON.parse(options.body)};return Response.json(detail)});const result=await new WebhookApi(api).retryDelivery(delivery,'  receiver recovered  ');assert.equal(result.body.delivery.cycle,2);assert.deepEqual(observed,{url:`/api/v1/webhook-deliveries/${delivery}/retry`,body:{reason:'receiver recovered'}});});

test('P07BTS05-admin-filter-is-encoded-and-retry-uses-admin-path',async()=>{const paths=[];const detail={delivery:deliveryView,attempts:[]};const api=new ApiClient(async(url,options)=>{if(url.endsWith('/auth/csrf'))return csrf('p07b-5');paths.push([url,options.method]);return Response.json(url.includes('?')?{items:[deliveryView],limit:25,offset:5,hasMore:false}:detail)});const webhooks=new WebhookApi(api);await webhooks.adminDeliveries('FAILED',25,5);await webhooks.adminRetry(delivery,'Investigated outage');assert.deepEqual(paths,[[`/api/v1/admin/webhook-deliveries?limit=25&offset=5&state=FAILED`,'GET'],[`/api/v1/admin/webhook-deliveries/${delivery}/retry`,'POST']]);});

test('P07BTS06-invalid-identities-versions-pagination-and-reasons-never-hit-network',()=>{let calls=0;const webhooks=new WebhookApi(new ApiClient(async()=>{calls++;return csrf('p07b-6')}));assert.throws(()=>webhooks.endpoint('not-a-uuid'),TypeError);assert.throws(()=>webhooks.setEndpointState(endpoint,true,0),TypeError);assert.throws(()=>webhooks.rotateSecret(endpoint,1.5),TypeError);assert.throws(()=>webhooks.deliveries(endpoint,101,0),TypeError);assert.throws(()=>webhooks.retryDelivery(delivery,'   '),TypeError);assert.throws(()=>webhooks.adminDeliveries('BROKEN'),TypeError);assert.equal(calls,0);});

test('P07BTS07-ordinary-reads-do-not-invent-secret-field',async()=>{const api=new ApiClient(async url=>Response.json(url.includes('?')?{items:[endpointView],limit:50,offset:0,hasMore:false}:endpointView));const webhooks=new WebhookApi(api);const listed=(await webhooks.endpoints()).items[0];const read=await webhooks.endpoint(endpoint);assert.equal(Object.hasOwn(listed,'signingSecret'),false);assert.equal(Object.hasOwn(read,'signingSecret'),false);});

const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
(async()=>{let failures=0;const rows=[];for(const c of cases){try{await c.run();console.log('PASS',c.id);rows.push(`<testcase name="${c.id}"/>`)}catch(e){failures++;console.error('FAIL',c.id,e.stack||e.message);rows.push(`<testcase name="${c.id}"><failure message="${escape(e.message)}"/></testcase>`)}}fs.mkdirSync('.evidence/client',{recursive:true});fs.writeFileSync('.evidence/client/webhook-results.xml',`<testsuite name="p07b-webhook-client" tests="${cases.length}" failures="${failures}" errors="0" skipped="0">${rows.join('\n')}</testsuite>`);console.log(`P07B_CLIENT_SUMMARY tests=${cases.length} failures=${failures}`);process.exitCode=failures?1:0})();
